modules:
  - edgeCase_jvmLib
  - edgeCase_jvmPlusAndroid
  - edgeCase_kmpSinglePlatform
  - edgeCase_noSources
  - edgeCase_serialization
  - edgeCase_wasmJsPlusWasmWasi
  - library
  - libraryCinterop
  - libraryNested
  - linuxWindowsShared
  - nativePlatform
  - nativeShared
