modules:
  - edgeCase_jvmLib
  - edgeCase_jvmPlusAndroid
  - edgeCase_kmpSinglePlatform
  - edgeCase_wasmJsPlusWasmWasi
  - library
  - libraryNested
  - linuxWindowsShared
  - nativePlatform
  - nativeShared

