/*
 * Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package org.jetbrains.amper.cli.test.utils

import kotlinx.serialization.json.Json
import org.jetbrains.amper.test.Dirs
import org.jetbrains.gradle.module.metadata.format.Module
import org.junit.jupiter.api.TestInfo
import java.nio.file.Path
import kotlin.io.path.deleteIfExists
import kotlin.io.path.div
import kotlin.io.path.exists
import kotlin.io.path.name
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.test.fail

/**
 * The directory containing the reference Gradle module metadata files.
 *
 * The `*.original_gradle.json` files it also contains are the metadata generated by KGP for the same test project.
 * They are not asserted against, they are only kept as a reference for the differences with the Gradle publication.
 */
private val goldenFilesRoot: Path = Dirs.amperSourcesRoot /
        "test-integration/amper-cli-test/testResources/gradleMetadata"

/**
 * Asserts that the Gradle module metadata generated at [actualFile] is the one described by the reference file named
 * `<name of the current test method>.[expectedFileNameSuffix]` in the `testResources/gradleMetadata` directory.
 *
 * On failure, the generated metadata is left next to the reference file with an extra `.tmp` extension, so that it can
 * be reviewed and promoted to the new reference (this is the convention of the other gold file tests, see the
 * `updateGoldFiles` project command).
 */
internal fun assertGradleMetadataEquals(expectedFileNameSuffix: String, actualFile: Path, testInfo: TestInfo) {
    val testName = testInfo.testMethod.get().name.replace(" ", "_")
    val goldenFile = goldenFilesRoot / "$testName.$expectedFileNameSuffix"

    val actualFileForReview = goldenFile.resolveSibling("${goldenFile.name}.tmp")
    actualFileForReview.writeText(actualFile.sanitizedGradleMetadata())

    if (!goldenFile.exists()) {
        fail("The reference file ${goldenFile.name} doesn't exist. If the metadata generated in " +
                "$actualFileForReview is correct, remove the '.tmp' extension to make it the reference.")
    }
    assertFileContentEquals(goldenFile, actualFileForReview)
    actualFileForReview.deleteIfExists()
}

/**
 * Reads this Gradle module metadata file, and returns its contents with the volatile parts replaced by placeholders.
 * The checksums and sizes of the published files depend on the environment, so they can't be asserted as such.
 */
private fun Path.sanitizedGradleMetadata(): String {
    val metadata = json.decodeFromString<Module>(readText())
    val sanitized = metadata.copy(
        variants = metadata.variants.map { variant ->
            variant.copy(
                files = variant.files.map {
                    it.copy(sha512 = "mocked", sha256 = "mocked", sha1 = "mocked", md5 = "mocked", size = -1)
                },
            )
        },
    )
    return json.encodeToString(sanitized)
}

private val json = Json {
    ignoreUnknownKeys = true
    isLenient = true
    prettyPrint = true
    prettyPrintIndent = "  "
}
